2011-Gemini-CAPSTONE/BridgeTheGap

- .vscode/settings.json
- dummy.js
- package.json
- public/dummy.html
- public/index.html
- script/seed.js
- server/api/data.js
- server/api/index.js
- server/db/models/data.js
- server/db/models/index.js
- created a BridgeTheGap model with a data table
- created a data model(dummy model)
- created route(works)
- have data in json
> feat: created data route with model and test works

- client/components/GuestHome.js
- client/components/index.js
- client/routes.js
- package-lock.json
- package.json
> T1:FE Created GuestHome component and render dummy data

- client/components/Tools.js
- client/components/navbar.js
- dummy.html
- dummy.json
- linearAndBand.js
> updated navbar and created links

- client/routes.js
> add data route

- client/components/Footer.js
- client/routes.js
> Finished footer

- client/components/Tools.js
- public/css/tools.css
> added dummy data to tools page

- public/css/tools.css
> article text changed to black

- client/components/Tools.js
- public/css/tools.css
> Fixed articles

- public/css/footer.css
> Fixed margin for footer

- client/components/navbar.js
- client/routes.js
> fixed links

- client/components/Footer.js
> Links now open new tabs

- client/components/GuestHome.js
- public/css/guesthome.css
> first attempt at some styling

- client/components/Tools.js
- client/components/navbar.js
- public/css/tools.css
changed Tools link to Resources
changed header to Articles --> maybe change it again to another header
> feat: updated link to Resources and change header to Articles

- client/components/GuestHome.js
- public/css/guesthome.css
> homepage quote added

- public/css/tools.css
updated the flex on cards articles to fit depending on screen size
> feat: update css flex on resources page

- client/components/navbar.js
- package-lock.json
- package.json
- public/css/navbar.css
> added styling to navbar

- client/components/navbar.js
>  fix two closing divs

- client/components/navbar.js
> change tools to resources

- client/components/charts/NewMap.js
added a legend for average salaries for female and male comparison in each state
> added average salaries for males and females

- articles.js
- client/components/Tools.js
- public/css/guesthome.css
- server/db/models/user.js
- server/index.js
> Aboutstart

- client/components/charts/NewMap.js
- dataInfo/femaleTech.js
- public/css/map.css
- server/db/models/data.js
- webpack.config.js
> Added css features to data

- client/components/charts/NewMap.js
- package-lock.json
- package.json
- public/css/map.css
> css for data map

- client/components/AuthForm.js
- public/css/auth.css
> styled login

- client/components/charts/NewMap.js
- public/css/map.css
> Moved legend on top of map/

- client/components/About.js
- client/components/Tools.js
- public/css/about.css
> about first hero/ jumbo feature 99% complete

- client/components/charts/NewMap.js
- public/css/footer.css
- public/css/map.css
> finished styling the legend and added a title to the legend

- server/api/data.js
- server/api/users.js
- server/db/models/user.js
> created routes for users and data

- client/components/AddSalary.js
- client/components/Assets/Team.js
- public/css/salary.css
> css for salary form

- client/components/About.js
- public/css/about.css
> added copywrite to about page and made small style changes

- client/components/navbar.js
- public/css/navbar.css
> render proper component for guest and users

- public/css/tools.css
redo css on article cards to have corners instead of a radius
> add corners on each card

- client/components/Data.js
- client/components/GuestHome.js
- client/components/StateInfo.js
- client/components/charts/NewMap.js
- client/components/index.js
- client/routes.js
- public/css/articlecard.css
- public/css/map.css
> created stateInfo component and the route with onclick

- client/components/ArticleCard.js
- package-lock.json
- package.json
- public/css/articlecard.css
-  changed article link to look like the wireframe
- install marteral UI icon package
- make sure to npm install
> fix: aritcle link

- client/components/StateInfo.js
- client/components/charts/BarChart.js
- public/index.html
> Started creating d3 chart

- client/components/StateInfo.js
- client/components/charts/BarChart.js
- client/components/charts/NewMap.js
> Put graph onto StateInfo page with correct scaling

- client/components/navbar.js
- public/css/navbar.css
> added activeClassName for UX/UI

- public/css/footer.css
> style changes to footer, introduced flex, corrected margins, img sizes

- public/css/about.css
> changed max width on certain jumbos to match HiFi mockuo

- client/components/StateInfo.js
- client/components/charts/BarChart.js
> Got job titles for state

- client/components/AuthForm.js
- public/css/auth.css
> styled and updated authform

- client/components/StateInfo.js
- client/components/charts/BarChart.js
- client/components/charts/NewMap.js
> Added all users info  into State info

- client/components/charts/BarChart.js
- client/components/charts/NewMap.js
> BarChart still working

- client/components/GuestHome.js
- client/components/charts/BarChart.js
- public/css/guesthome.css
bar chart shows the number of job titles in the team
> finish bar count

- client/components/StateInfo.js
- client/components/charts/BarChart.js
- client/components/charts/NewMap.js
- client/components/userTable.js
- package-lock.json
- package.json
- public/css/footer.css
- public/css/stateInfo.css
- public/style.css
> State info page styled

- client/components/StateInfo.js
- client/components/charts/BarChart.js
- client/components/charts/NewMap.js
- client/components/userTable.js
- package-lock.json
- package.json
- public/css/stateInfo.css
> userTable finished

- client/components/StateInfo.js
- client/components/charts/BarChart.js
- client/components/charts/NewMap.js
- client/components/userTable.js
- package-lock.json
- package.json
- public/css/footer.css
- public/css/stateInfo.css
- public/style.css
> User table css

- client/components/About.js
- client/components/GuestHome.js
- public/css/footer.css
- public/css/navbar.css
> changed footer and nav margins a bit

- client/components/GuestHome.js
> signup message for guests

- articles.js
- client/components/Footer.js
> Fix article description and change link to footer logo

- client/components/StateInfo.js
- client/components/charts/NewMap.js
> Add red color if no users and text for next page stating no users
